# https://github.com/dragonflydb/dragonfly-operator
# https://www.dragonflydb.io/docs/getting-started/kubernetes-operator
# https://www.dragonflydb.io/docs/getting-started/kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dragonfly-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dragonfly-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: dragonfly-operator
    repoURL: ghcr.io/dragonflydb/dragonfly-operator/helm
    targetRevision: v1.1.11
    helm:
      releaseName: dragonfly-operator
      valuesObject:
        fullnameOverride: dragonfly-operator
        
        additionalLabels:
          app: dragonfly-operator

        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi

        serviceMonitor:
          enabled: true
          interval: 60s

        nodeSelector:
          node-role.kubernetes.io/homelab: homelab
---