# https://opentelemetry.io/docs/platforms/kubernetes/getting-started/#daemonset-collector
# https://opentelemetry.io/docs/platforms/kubernetes/operator/
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: daemonset
  namespace: opentelemetry-collector
spec:
  mode: daemonset
  hostNetwork: true
  image: docker.io/library/otel/opentelemetry-collector-k8s:v0.130.1
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 64Mi
  #   limits:
  #     cpu: 200m
  #     memory: 128Mi
  config:
    receivers:
      jaeger:
        protocols:
          grpc: {}
    processors: {}

    exporters:
      debug:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [debug]
---