# https://artifacthub.io/packages/helm/cert-manager/cert-manager
# https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.18.2
    helm:
      releaseName: cert-manager
      valuesObject:
        fullnameOverride: cert-manager
        namespace: cert-manager

        crds:
          enabled: true
          keep: true

        # https://cert-manager.io/docs/usage/gateway/
        config:
          apiVersion: controller.config.cert-manager.io/v1alpha1
          kind: ControllerConfiguration
          enableGatewayAPI: true

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

        prometheus:
          servicemonitor:
            enabled: true
            interval: 60s

        nodeSelector:
          node-role.kubernetes.io/homelab: homelab
---