# https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
---
# Let's Encrypt Prod
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
---
# Let's Encrypt staging
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
---
# # Buypass
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: buypass
#   annotations:
#     argocd.argoproj.io/sync-wave: "3"
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
# spec:
#   acme:
#     email: ${ACME_EMAIL} # required for Buypass
#     server: https://api.buypass.com/acme/directory
#     privateKeySecretRef:
#       name: buypass
#     solvers:
#     - dns01:
#         cloudflare:
#           apiTokenSecretRef:
#             name: cloudflare-api-token
#             key: api-token
# ---