---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
data:
  api-token: ${CLOUDFLARE_API_TOKEN}
---