# https://gateway-api.sigs.k8s.io/guides/#installing-gateway-api
# https://github.com/kubernetes-sigs/gateway-api
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    targetRevision: v1.3.0
    path: config/crd/experimental
---