# https://gateway.envoyproxy.io/docs/api/extension_types/#envoyproxyspec
# https://gateway.envoyproxy.io/docs/tasks/operations/deployment-mode/#merged-gateways-deployment
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy-config
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  mergeGateways: true
---