# https://artifacthub.io/packages/helm/longhorn/longhorn
# https://longhorn.io/docs/1.8.1/snapshots-and-backups/backup-and-restore/set-backup-target/
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.9.0
    helm:
      namespaceOverride: longhorn-system # mandatory namespace for this helm chart

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/hostname: longhorn.${BASE_DOMAIN}
        host: longhorn.${BASE_DOMAIN}
        tls: true
        tlsSecret: longhorn-ingress-tls
        secureBackends: false

      global:
        nodeSelector:
          node-role.kubernetes.io/homelab: homelab