# https://artifacthub.io/packages/helm/longhorn/longhorn
# https://longhorn.io/docs/1.8.1/snapshots-and-backups/backup-and-restore/set-backup-target/
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.9.0
    helm:
      releaseName: longhorn
      valuesObject:
        namespaceOverride: longhorn-system # mandatory namespace for this helm chart

        metrics:
          serviceMonitor:
            enabled: true
            interval: 60s

        global:
          nodeSelector:
            node-role.kubernetes.io/homelab: homelab
---