# https://github.com/nextcloud/helm
# https://artifacthub.io/packages/helm/nextcloud/nextcloud
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: nextcloud
    repoURL: https://nextcloud.github.io/helm
    targetRevision: 7.0.0
    helm:
      releaseName: nextcloud
      valuesObject:
        fullnameOverride: nextcloud

        nextcloud:
          host: nextcloud.${BASE_DOMAIN}
          existingSecret:
            enabled: true
            usernameKey: nextcloud-username # TODO
            passwordKey: nextcloud-password # TODO
            tokenKey: "" # TODO
            smtpUsernameKey: smtp-username # TODO
            smtpPasswordKey: smtp-password # TODO
            smtpHostKey: smtp-host # TODO
        
        internalDatabase:
          enabled: false

        externalDatabase:
          enabled: true
          type: postgresql
          existingSecret:
            enabled: true
            secretName: nameofsecret # TODO
            usernameKey: db-username # TODO
            passwordKey: db-password # TODO
            hostKey: db-hostname-or-ip # TODO
            databaseKey: db-name # TODO

        cronjob:
          enabled: true

        persistence:
          enabled: true
          storageClass: longhorn-crypto
          accessMode: ReadWriteOnce
          size: 200Gi

        # hpa:
        #   enabled: true
        #   cputhreshold: 60
        #   minPods: 1
        #   maxPods: 5

        metrics:
          serviceMonitor:
            enabled: true
            interval: 60s

        rbac:
          enabled: true

        nodeSelector:
          node-role.kubernetes.io/homelab: homelab
---