# https://artifacthub.io/packages/helm/nextcloud/nextcloud
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: nextcloud
    repoURL: https://nextcloud.github.io/helm
    targetRevision: 7.0.0
    helm:
      service:
        annotations:
          traefik.ingress.kubernetes.io/service.sticky.cookie: "true"