---
# https://github.com/minio/operator/blob/master/helm/tenant/templates/tenant-configuration.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-tenant-credentials
  namespace: minio-tenant
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER=${MINIO_ROOT_USER}
    export MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
---