---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto
  resources:
    requests:
      storage: 100Gi
---