---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-crypto
  resources:
    requests:
      storage: 100Gi
---