# https://github.com/immich-app/immich-charts
# https://artifacthub.io/packages/helm/immich/immich
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: immich
    repoURL: ghcr.io/immich-app/immich-charts
    targetRevision: 0.9.3
    helm:
      releaseName: immich
      valuesObject:
        global:
          fullnameOverride: immich

        immich:
          metrics:
            enabled: true # serviceMonitor
          persistence:
            library:
              existingClaim: immich
        
        machine-learning:
          persistence:
            cache:
              enabled: true
              size: 10Gi
              type: pvc
              accessMode: ReadWriteMany
              storageClass: longhorn-crypto

        env:
          REDIS_HOSTNAME: dragonfly.svc.cluster.local:6379 # TODO: check value
          DB_HOSTNAME: # TODO: check vlaue
---