---
apiVersion: v1
kind: Service
metadata:
  name: gigapipe
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: gigapipe
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: ClusterIP
---