# https://artifacthub.io/packages/helm/external-dns/external-dns
# https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.18.0
    helm:
      releaseName: external-dns
      valuesObject:
        fullnameOverride: external-dns
        namespaced: true

        # force the DNS record IP address
        extraArgs:
          - default-targets=${EXTERNAL_IP}

        sources:
          - service
          - gateway-httproute
          - gateway-grpcroute
          - gateway-tlsroute
          - gateway-tcproute
          - gateway-udproute

        # "sync" policy has issues:
        # https://github.com/kubernetes-sigs/external-dns/issues/4059
        policy: upsert-only

        provider:
          name: cloudflare

        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: api-token

        serviceMonitor:
          enabled: true
          interval: 60s

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

        nodeSelector:
          node-role.kubernetes.io/homelab: homelab
---