# https://github.com/InseeFrLab/s3-operator
# https://github.com/InseeFrLab/helm-charts/tree/master/charts/s3-operator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: s3-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: s3-operator
    repoURL: https://inseefrlab.github.io/helm-charts
    targetRevision: 0.6.0 # helm search repo inseefrlab/s3-operator --versions
    helm:
      releaseName: s3-operator
      valuesObject:
        
---