# https://github.com/InseeFrLab/s3-operator/blob/main/README.md
--- # TODO: all of it..
apiVersion: s3.onyxia.sh/v1alpha1
kind: Bucket
metadata:
  labels:
    app.kubernetes.io/name: bucket
    app.kubernetes.io/instance: bucket-sample
    app.kubernetes.io/part-of: s3-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: s3-operator
  name: bucket-sample
spec:
  # Bucket name (on S3 server, as opposed to the name of the CR)
  name: dummy-bucket

  # Paths to create on the bucket 
  # As it is not possible to create empty paths on a S3 server, (limitation of either S3,
  # or at least Minio, the only currently implemented provider), this will actually create
  # a .keep file at the deepest folder in the path.
  paths:
    - a_path
    - another/deeper/path
  
  # Quota to set on the bucket, in bytes (so 1000000000 would be 1GB).
  # This is split over two different parameters, although there is only one actual quota
  #   - "default" is required, and is used as the baseline
  #   - "override" is optional, and as the name implies, takes precedence over "default"
  # Though clumsy, this pattern (for lack of a better word) allows to easily change the
  # default quota for every buckets without impacting the ones that might have received
  # a manual change. If this is not useful to you, you can safely skip using "override".
  quota:
    default: 10000000    
    # override: 20000000
  
  # Optionnal, let empty if you have configured the default s3 else use an existing s3Instance
  s3InstanceRef: "s3-default-instance"
---