# https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-pg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.io/charts
    targetRevision: 0.24.0
    helm:
      fullnameOverride: cloudnative-pg
      namespaceOverride: cloudnative-pg

      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 256Mi

      nodeSelector:
        node-role.kubernetes.io/homelab: homelab