---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  username: ${GRAFANA_USERNAME}
  password: ${GRAFANA_PASSWORD}
---